version: '3'
services:
  mynotesDB:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5435:5432
    container_name: mynotesDB
    environment:
      - POSTGRES_USER=mynotes
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mynotes
    volumes:
      - ./mynotesdb_data:/var/lib/postgresql/data