spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5435/mynotes
    username: mynotes
    password: password
    name: mynotes

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'

ru:
  vsu:
    csf:
      my-note:
        max-file-amount: 20
        max-file-size-mb: 12
