spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5435/mynotesdb
    username: mynotes
    password: password
    name: mynotes

ru:
  vsu:
    csf:
      my-note:
        max-file-amount: 20
        max-file-size-mb: 12
